version: '3.7'

services:
  ####################### POSTGRES #######################
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - webapi_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: h.darani@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - webapi_network
    restart: unless-stopped
    depends_on:
      - postgres
  
    ####################### REDIS #######################
  redis:
    image: redis:7
    container_name: redis_container
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis 
    ports:
      - "6379:6379"
    networks:
      - webapi_network

####################### VOLUME AND NETWORKS #######################
volumes:
  postgres:
  redis:
  pgadmin:

networks:
  webapi_network:
    driver: bridge